# resource config
exp_name: fmnist-conv2

###################################### 16

# checkpoint config
model: conv2
alg: fedavg
gpu_ids: [0, 1]
# pre_train: True

# dataset config
dataset: fmnist
batch_size: 32

#################################################

# optim: sgd
optim: sgd
learning_rate: 0.01

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 20
min_lr: 0.0

# federal config
federal: True
non_iid: shards
workers: 100
active_workers: 2
federal_round: 70
local_epoch: 5

###################################### 16

clusters: 25
logits_batch_limit: 20

