# resource config
exp_name: fmnist-conv2

###################################### 16

# checkpoint config
model: vgg16
alg: fedla
gpu_ids: [0, 1]
# pre_train: True

# dataset config
dataset: cifar10
batch_size: 32

#################################################

# optim: sgd
optim: sgd
learning_rate: 0.1

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 20
min_lr: 0.0

# federal config
federal: True
non_iid: hetero
workers: 100
active_workers: 10
federal_round: 150
local_epoch: 10

###################################### 16

clusters: 50
logits_batch_limit: 20

