# resource config
exp_name: fmnist-conv2

###################################### 16
# checkpoint config
model: conv2
alg: fedla
gpu_ids: [0, 1]
# pre_train: True

# dataset config
dataset: fmnist
batch_size: 32

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.01

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 15
min_lr: 0.0

# federal config
federal: True
non_iid: hetero
workers: 100
active_workers: 2
federal_round: 30
local_epoch: 5

###################################### 16
# federal_round: 11
# local_epoch: 1
logits_batch_limit: 20

merge_batch: 0
merge_epoch: 0

#KD_BATCH: 128
#KD_EPOCH: 10

#KD_BATCH: 32
#KD_EPOCH: 3

KD_BATCH: 0
KD_EPOCH: 0

ALPHA: 1
BETA: 8
