# resource config
exp_name: cifar100-mobilenetV2

# checkpoint config
model: mobilenetV2
alg: feddas
gpu_ids: [0]
dir_alpha: 0.3

# dataset config
dataset: cifar100
batch_size: 128

# optimizer config
optim: sgd
learning_rate: 0.05

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 20
min_lr: 0.0

# federal config
non_iid: hetero
workers: 50
active_workers: 5
federal_round: 200

## center train
local_epoch: 2
test_batch_limit: 5

clusters: 20
cons_alpha: 0.6
step_cluster: 10