# resource :config
exp_name: cifar100-resnet110

# checkpoint config
model: resnet110
alg: fedavg
gpu_ids: [0, 1]
# pre_train: True

# dataset config
dataset: cifar100
batch_size: 32

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.01

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 50
min_lr: 0.0

# federal config
federal: True
non_iid: hetero
workers: 100
active_workers: 10
federal_round: 500

local_epoch: 10
test_batch_limit: 5
