# resource config
exp_name: cifar100-mobilenetV2

# checkpoint config
model: mobilenetV2
alg: fedavg
gpu_ids: [0]

# dataset config
dataset: cifar100
batch_size: 128
dir_alpha: 0.3


# optimizer config
optim: sgd
learning_rate: 0.05

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 20
min_lr: 0.0

# federal config
non_iid: hetero
workers: 50
active_workers: 10
federal_round: 1000

## center train
local_epoch: 2
test_batch_limit: 5
