# resource :config
exp_name: emnist-resnet110

# checkpoint config
model: resnet110
alg: fedavg
gpu_ids: [0]
# pre_train: True

# dataset config
dataset: emnist
batch_size: 32

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.01

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 50
min_lr: 0.0

# federal config
federal: True
non_iid: shards
workers: 62
active_workers: 6
federal_round: 100

local_epoch: 1
batch_limit: 100
test_batch_limit: 30

clusters: 20
step_cluster: 3
