# resource config
exp_name: fmnist-conv2

# checkpoint config
model: conv2
alg: fedavg
gpu_ids: [0]
dir_alpha: 0.3

# dataset config
dataset: fmnist
batch_size: 32

# optimizer config
optim: sgd
learning_rate: 0.01

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 10
min_lr: 0.0

# federal config
federal: True
non_iid: hetero
workers: 100
active_workers: 3
#workers: 1
#active_work:qers: 1
federal_round: 15
local_epoch: 5

# feddas
clusters: 12
step_cluster: 1
#clusters: 12
#step_cluster: 1
drag: 0.0
# threshold: 0.05
threshold: -0.01
cons_alpha: 0.3

logits_batch_limit: 20
