# resource config
exp_name: fmnist-conv2

# checkpoint config
model: conv2
alg: criticalfl
gpu_ids: [0, 1]

# dataset config
dataset: fmnist
batch_size: 32

# optimizer config
optim: sgd
learning_rate: 0.1

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 10
min_lr: 0.0

# federal config
federal: True
non_iid: hetero
workers: 100
active_workers: 3
federal_round: 50
local_epoch: 5

# fedla
clusters: 12
drag: 0.0
# threshold: 0.05
threshold: -0.01
step_cluster: 1
cons_alpha: 0.3

logits_batch_limit: 20

