# resource config
exp_name: fmnist-conv2

# checkpoint config
model: conv2
alg: fedla
gpu_ids: [0, 1]

# dataset config
dataset: fmnist
batch_size: 32

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.1

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 10
min_lr: 0.0


# federal config
federal: True
non_iid: hetero
workers: 100
active_workers: 3
federal_round: 15
local_epoch: 10

# fedla
clusters: 10
drag: 0.6
threshold: 0.05

logits_batch_limit: 20

