# resource config
exp_name: cifar10-non-iid

# checkpoint config
model: vgg16
alg: fedavg
# pre_train: True

# dataset config
dataset: cifar10
batch_size: 32

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.01

# scheduler config warm_steps: 20
scheduler: warmup_cos_lr
warm_steps: 20
min_lr: 0.0

# federal config federal_round: 150
federal: True
non_iid: iid
workers: 20
active_workers: 4
federal_round: 150

local_epoch: 5
test_batch_limit: 10

check_inter: 10
fedavg_test: True
backward: 1
info_norm: 3

