# experiment config
exp_name: tinyimagenet-shufflenet

# checkpoint config
model: shufflenetV2
alg: fedavg
gpu_ids: [0, 1]
# pre_train: True

# dataset config
dataset: tinyimagenet
batch_size: 64

# optimizer config
# optim: sgd
optim: rmsprop
learning_rate: 0.01

# scheduler config
scheduler: step_lr
warm_steps: 20
min_lr: 0.0

# federal config
federal: True
non_iid: hetero
workers: 5
active_workers: 3
federal_round: 100

local_epoch: 10
test_batch_limit: 5
