# experiment config
exp_name: tinyimagenet-shufflenet

# checkpoint config
model: shufflenetV2
alg: fedavg
gpu_ids: [0]
# pre_train: True

# dataset config
dataset: tinyimagenet
batch_size: 128

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.01

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 200
min_lr: 0.0

# federal config
federal: True
non_iid: hetero
workers: 10
active_workers: 5
federal_round: 1000

local_epoch: 2
test_batch_limit: 5
